### ISSUE TITLE
rbenv+bundler deploy: mixlib/log/version (LoadError)

### ISSUE THREAD

**Issue by hedgehog** [chef/mixlib-log#3]
I've been following the rbenv suggestions for production deployments.
All works well for the 148 gems being deployed.  However, I am constantly hitting this error with mixlib-log, and only mixlib-log:

```
    /home/ubuntu/project/vendor/bundle/ruby/1.9.1/gems/mixlib-log-1.3.0/lib/mixlib/log.rb:20:in `require': no such file to load -- mixlib/log/version (LoadError)
from /home/ubuntu/project/vendor/bundle/ruby/1.9.1/gems/mixlib-log-1.3.0/lib/mixlib/log.rb:20:in `<top (required)>'
from /home/ubuntu/project/vendor/bundle/ruby/1.9.1/gems/chef-0.10.8/lib/chef/log.rb:21:in `require'
from /home/ubuntu/project/vendor/bundle/ruby/1.9.1/gems/chef-0.10.8/lib/chef/log.rb:21:in `<top (required)>'
from /home/ubuntu/project/vendor/bundle/ruby/1.9.1/gems/chef-0.10.8/lib/chef.rb:23:in `require'
from /home/ubuntu/project/vendor/bundle/ruby/1.9.1/gems/chef-0.10.8/lib/chef.rb:23:in `<top (required)>'
from /home/ubuntu/project/vendor/bundle/ruby/1.9.1/gems/chef-0.10.8/lib/chef/application/solo.rb:18:in `require'
from /home/ubuntu/project/vendor/bundle/ruby/1.9.1/gems/chef-0.10.8/lib/chef/application/solo.rb:18:in `<top (required)>'
from /home/ubuntu/project/vendor/bundle/ruby/1.9.1/gems/chef-0.10.8/bin/chef-solo:23:in `require'
from /home/ubuntu/project/vendor/bundle/ruby/1.9.1/gems/chef-0.10.8/bin/chef-solo:23:in `<top (required)>'
from /home/ubuntu/project/vendor/bundle/ruby/1.9.1/bin/chef-solo:19:in `load'
from /home/ubuntu/project/vendor/bundle/ruby/1.9.1/bin/chef-solo:19:in `<main>'
```

The bundle install command is (as deploy user):

```
 bundle install --deployment --binstubs --shebang ruby-local-exec --gemfile /home/ubuntu/project/Gemfile --path /home/ubuntu/project/vendor/bundle
```

The work around, after the `bundle install`, is to run (as deploy user):

```
bin/bundle exec gem install mixlib-log
```

Then all is OK until the next time the application deploys, then we repeat :)

The issues seems to be that the gemspec does not like bundler, since the `log` sub-folder and files are missing:

```
$ ls -la /home/ubuntu/project/vendor/bundle/ruby/1.9.1/gems/mixlib-log-1.3.0/lib/mixlib
total 16
drwxr-xr-x 2 ubuntu ubuntu 4096 2012-03-01 08:31 .
drwxr-xr-x 3 ubuntu ubuntu 4096 2012-03-01 08:31 ..
-rw-r--r-- 1 ubuntu ubuntu 5208 2012-03-01 08:31 log.rb
```

The gem is indeed missing the files:

```
$ bin/bundle exec gem contents mixlib-log
/home/ubuntu/project/vendor/bundle/ruby/1.9.1/gems/mixlib-log-1.3.0/LICENSE
/home/ubuntu/project/vendor/bundle/ruby/1.9.1/gems/mixlib-log-1.3.0/NOTICE
/home/ubuntu/project/vendor/bundle/ruby/1.9.1/gems/mixlib-log-1.3.0/README.rdoc
/home/ubuntu/project/vendor/bundle/ruby/1.9.1/gems/mixlib-log-1.3.0/lib/mixlib/log.rb
```

And the installed specification is:

```
$ cat /home/ubuntu/project/vendor/bundle/ruby/1.9.1/specifications/mixlib-log-1.3.0.gemspec 
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "mixlib-log"
  s.version = "1.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Opscode, Inc."]
  s.date = "2011-03-23"
  s.email = "info@opscode.com"
  s.extra_rdoc_files = ["README.rdoc", "LICENSE", "NOTICE"]
  s.files = ["README.rdoc", "LICENSE", "NOTICE"]
  s.homepage = "http://www.opscode.com"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.17"
  s.summary = "A gem that provides a simple mixin for log functionality"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
```

**Comment by mixtli** [comment]
This is coming up for me as well.  Exact same issue.   It seem to happen only in production.
