### ISSUE TITLE
`initialize': wrong number of arguments when passing time to ::init

### ISSUE THREAD

**Issue by jasonwbarnett** [chef/mixlib-log#55]
# Version:

v3.0.1

# Environment:

RHEL 6
ChefDK v4.0.60

# Scenario:

Trying to leverage the built-in log rotation

# Steps to Reproduce:

```ruby
require 'mixlib/log'

class Log
  extend Mixlib::Log
end

Log.init('/tmp/logfile', 7)
```

# Expected Result:

I would expect this to start logging to `/tmp/logfile` and to automatically rotate every 7 days.

# Actual Result:

```text
Traceback (most recent call last):
        6: from /opt/chefdk/embedded/bin/irb:11:in `<main>'
        5: from (irb):7
        4: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/mixlib-log-3.0.1/lib/mixlib/log.rb:83:in `init'
        3: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/mixlib-log-3.0.1/lib/mixlib/log.rb:177:in `logger_for'
        2: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/mixlib-log-3.0.1/lib/mixlib/log.rb:177:in `new'
        1: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/mixlib-log-3.0.1/lib/mixlib/log/logger.rb:35:in `initialize'
ArgumentError (wrong number of arguments (given 2, expected 1))
```

**Comment by jasonwbarnett** [comment]
I already tested rolling back this commit and it fixes the problem: https://github.com/chef/mixlib-log/pull/37/files#diff-146fbb2d220c80b0e0f5315fac87e2deR173
