### ISSUE TITLE
rspec testsuite fails with ruby 3.3.0dev

### ISSUE THREAD

**Issue by mtasaka** [chef/mixlib-log#73]
With ruby 3.3.0dev ( I tested https://github.com/ruby/ruby/commit/6d7730ab98a0cb8708ff7f1ff163458cc3e1e0cd ), mixlib-log git head ( https://github.com/chef/mixlib-log/commit/8643e3348de7c5c0ed3ffeb80f5300d767f450ac  ) rspec testsuite causes error like:

```
$ rspec spec
.....
Failures:

  1) Mixlib::Log::Child can query the parent's level at debug
     Failure/Error: logger.send(method_name)

     NoMethodError:
       undefined method `[]' for nil
     # ./lib/mixlib/log.rb:131:in `block (2 levels) in <module:Log>'
     # ./lib/mixlib/log/child.rb:41:in `block (2 levels) in <class:Child>'
     # ./spec/mixlib/log/child_spec.rb:95:in `block (4 levels) in <top (required)>'

  2) Mixlib::Log::Child can query the parent's level at info
     Failure/Error: logger.send(method_name)

     NoMethodError:
       undefined method `[]' for nil
     # ./lib/mixlib/log.rb:131:in `block (2 levels) in <module:Log>'
     # ./lib/mixlib/log/child.rb:41:in `block (2 levels) in <class:Child>'
     # ./spec/mixlib/log/child_spec.rb:95:in `block (4 levels) in <top (required)>'

  3) Mixlib::Log::Child can query the parent's level at warn
     Failure/Error: logger.send(method_name)

     NoMethodError:
       undefined method `[]' for nil
     # ./lib/mixlib/log.rb:131:in `block (2 levels) in <module:Log>'
     # ./lib/mixlib/log/child.rb:41:in `block (2 levels) in <class:Child>'
     # ./spec/mixlib/log/child_spec.rb:95:in `block (4 levels) in <top (required)>'

  4) Mixlib::Log::Child can query the parent's level at error
     Failure/Error: logger.send(method_name)

     NoMethodError:
       undefined method `[]' for nil
     # ./lib/mixlib/log.rb:131:in `block (2 levels) in <module:Log>'
     # ./lib/mixlib/log/child.rb:41:in `block (2 levels) in <class:Child>'
     # ./spec/mixlib/log/child_spec.rb:95:in `block (4 levels) in <top (required)>'

  5) Mixlib::Log::Child can query the parent's level at fatal
     Failure/Error: logger.send(method_name)

     NoMethodError:
       undefined method `[]' for nil
     # ./lib/mixlib/log.rb:131:in `block (2 levels) in <module:Log>'
     # ./lib/mixlib/log/child.rb:41:in `block (2 levels) in <class:Child>'
     # ./spec/mixlib/log/child_spec.rb:95:in `block (4 levels) in <top (required)>'

  6) Mixlib::Log should set the log level using the binding form,  with :trace, :debug, :info, :warn, :error, or :fatal
     Failure/Error: expect(Logit.logger.level).to eq(constant)

     NoMethodError:
       undefined method `[]' for nil
     # ./spec/mixlib/log_spec.rb:109:in `block (3 levels) in <top (required)>'
     # ./spec/mixlib/log_spec.rb:107:in `each'
     # ./spec/mixlib/log_spec.rb:107:in `block (2 levels) in <top (required)>'

  7) Mixlib::Log should set the log level using the method form, with :trace, :debug, :info, :warn, :error, or :fatal
     Failure/Error: expect(Logit.logger.level).to eq(constant)

     NoMethodError:
       undefined method `[]' for nil
     # ./spec/mixlib/log_spec.rb:132:in `block (3 levels) in <top (required)>'
     # ./spec/mixlib/log_spec.rb:130:in `each'
     # ./spec/mixlib/log_spec.rb:130:in `block (2 levels) in <top (required)>'

  8) Mixlib::Log should pass other method calls directly to logger
     Failure/Error: logger.send(method_name)

     NoMethodError:
       undefined method `[]' for nil
     # ./lib/mixlib/log.rb:131:in `block (2 levels) in <module:Log>'
     # ./spec/mixlib/log_spec.rb:150:in `block (3 levels) in <top (required)>'
     # ./spec/mixlib/log_spec.rb:145:in `block (2 levels) in <top (required)>'

  9) Mixlib::Log should pass add method calls directly to logger
     Failure/Error: logger.send(method_name)

     NoMethodError:
       undefined method `[]' for nil
     # ./lib/mixlib/log.rb:131:in `block (2 levels) in <module:Log>'
     # ./spec/mixlib/log_spec.rb:159:in `block (2 levels) in <top (required)>'

Finished in 0.02143 seconds (files took 0.07924 seconds to load)
44 examples, 9 failures

```

This is due to change in ruby Logger:
https://github.com/ruby/ruby/commit/194520f80e1cdb71faa055d731450855a1ddb8d1
https://github.com/ruby/logger/pull/85

and almost the same fix as https://github.com/steveklabnik/mono_logger/pull/12 is needed.

**Comment by tpowell-progress** [comment]
See also: https://github.com/steveklabnik/mono_logger/pull/12
